#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Styling, testing and building your project before committing'

# Check Prettier standards
yarn check-format ||
(
    echo 'Your styling looks unacceptable. Prettier Check Failed. Run npm run format, add changes and try committing again.';
    false;
)

# Check ESLint Standards
yarn check-lint ||
(
    echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
    false; 
)

# Check tsconfig standards
yarn check-types ||
(
    echo 'Failed Type check. Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo 'Code looks good to me.'

